export const allVehicles = [
    {
        id: 765,
        make: "Honda",
        model: "Passport",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "992.36",
        available: true,
    },
    {
        id: 2380,
        make: "Ford",
        model: "Mustang",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "848.73",
        available: true,
    },
    {
        id: 2417,
        make: "Tesla",
        model: "Model S",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "976.07",
        available: true,
    },
    {
        id: 1593,
        make: "Volkswagen",
        model: "Passat",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "133.03",
        available: true,
    },
    {
        id: 880,
        make: "Toyota",
        model: "Prius",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "927.35",
        available: true,
    },
    {
        id: 1148,
        make: "BMW",
        model: "series 1",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "306.02",
        available: true,
    },
    {
        id: 674,
        make: "Porsche",
        model: "Boxter",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "164.53",
        available: true,
    },
    {
        id: 532,
        make: "Kia",
        model: "Sportage",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "986.71",
        available: true,
    },
    {
        id: 806,
        make: "Jeep",
        model: "Cherokee",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "254.04",
        available: true,
    },
    {
        id: 1369,
        make: "Honda",
        model: "Passport",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "169.22",
        available: true,
    },
    {
        id: 2210,
        make: "Ford",
        model: "Taurus",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "854.18",
        available: true,
    },
    {
        id: 1752,
        make: "Tesla",
        model: "Model 3",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "310.46",
        available: true,
    },
    {
        id: 2026,
        make: "Volkswagen",
        model: "Passat",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "861.00",
        available: true,
    },
    {
        id: 527,
        make: "Toyota",
        model: "Camry",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "626.23",
        available: true,
    },
    {
        id: 1088,
        make: "BMW",
        model: "series 2",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "241.62",
        available: true,
    },
    {
        id: 1314,
        make: "Porsche",
        model: "Boxter",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "722.46",
        available: true,
    },
    {
        id: 1181,
        make: "Kia",
        model: "Sportage",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "841.56",
        available: true,
    },
    {
        id: 1968,
        make: "Jeep",
        model: "Cherokee",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "136.24",
        available: true,
    },
    {
        id: 1506,
        make: "Honda",
        model: "Accord",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "979.56",
        available: true,
    },
    {
        id: 2262,
        make: "Ford",
        model: "Mustang",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "82.83",
        available: true,
    },
    {
        id: 1478,
        make: "Tesla",
        model: "Model Y",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "884.18",
        available: true,
    },
    {
        id: 1450,
        make: "Volkswagen",
        model: "Golf",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "766.83",
        available: true,
    },
    {
        id: 2410,
        make: "Toyota",
        model: "Prius",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "344.27",
        available: true,
    },
    {
        id: 634,
        make: "BMW",
        model: "series 2",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "113.03",
        available: true,
    },
    {
        id: 2135,
        make: "Porsche",
        model: "Cayman",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "120.16",
        available: true,
    },
    {
        id: 903,
        make: "Kia",
        model: "Sportage",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "305.34",
        available: true,
    },
    {
        id: 2460,
        make: "Jeep",
        model: "Liberty",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "819.88",
        available: true,
    },
    {
        id: 1594,
        make: "Honda",
        model: "Civic",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "511.47",
        available: true,
    },
    {
        id: 1503,
        make: "Ford",
        model: "Taurus",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "344.14",
        available: true,
    },
    {
        id: 2379,
        make: "Tesla",
        model: "Model Y",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "240.29",
        available: true,
    },
    {
        id: 1694,
        make: "Volkswagen",
        model: "Golf",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "498.50",
        available: true,
    },
    {
        id: 1888,
        make: "Toyota",
        model: "Corolla",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "849.54",
        available: true,
    },
    {
        id: 1927,
        make: "BMW",
        model: "series 1",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "48.93",
        available: true,
    },
    {
        id: 708,
        make: "Porsche",
        model: "Boxter",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "902.16",
        available: true,
    },
    {
        id: 771,
        make: "Kia",
        model: "Telluride",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "441.82",
        available: true,
    },
    {
        id: 1424,
        make: "Jeep",
        model: "Liberty",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "770.29",
        available: true,
    },
    {
        id: 1236,
        make: "Honda",
        model: "Civic",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "598.34",
        available: true,
    },
    {
        id: 529,
        make: "Ford",
        model: "Mustang",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "357.18",
        available: true,
    },
    {
        id: 975,
        make: "Tesla",
        model: "Model S",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "271.56",
        available: true,
    },
    {
        id: 547,
        make: "Volkswagen",
        model: "Passat",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "823.52",
        available: true,
    },
    {
        id: 743,
        make: "Toyota",
        model: "Prius",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "210.35",
        available: true,
    },
    {
        id: 576,
        make: "BMW",
        model: "series 1",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "26.97",
        available: true,
    },
    {
        id: 1285,
        make: "Porsche",
        model: "Boxter",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "901.32",
        available: true,
    },
    {
        id: 2042,
        make: "Kia",
        model: "Telluride",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "610.84",
        available: true,
    },
    {
        id: 1924,
        make: "Jeep",
        model: "Liberty",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "613.49",
        available: true,
    },
    {
        id: 1020,
        make: "Honda",
        model: "Civic",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "963.33",
        available: true,
    },
    {
        id: 1828,
        make: "Ford",
        model: "Mustang",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "271.92",
        available: true,
    },
    {
        id: 708,
        make: "Tesla",
        model: "Model 3",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "737.14",
        available: true,
    },
    {
        id: 953,
        make: "Volkswagen",
        model: "Golf",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "495.05",
        available: true,
    },
    {
        id: 613,
        make: "Toyota",
        model: "Prius",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "773.57",
        available: true,
    },
    {
        id: 806,
        make: "BMW",
        model: "series 1",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "79.21",
        available: true,
    },
    {
        id: 2295,
        make: "Porsche",
        model: "Cayman",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "364.45",
        available: true,
    },
    {
        id: 1553,
        make: "Kia",
        model: "Telluride",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "348.57",
        available: true,
    },
    {
        id: 2212,
        make: "Jeep",
        model: "Cherokee",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "711.91",
        available: true,
    },
    {
        id: 2246,
        make: "Honda",
        model: "Accord",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "362.75",
        available: true,
    },
    {
        id: 708,
        make: "Ford",
        model: "F150",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "982.92",
        available: true,
    },
    {
        id: 1033,
        make: "Tesla",
        model: "Model S",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "519.21",
        available: true,
    },
    {
        id: 2385,
        make: "Volkswagen",
        model: "Passat",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "161.21",
        available: true,
    },
    {
        id: 1960,
        make: "Toyota",
        model: "Prius",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "265.20",
        available: true,
    },
    {
        id: 1843,
        make: "BMW",
        model: "series 1",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "393.67",
        available: true,
    },
    {
        id: 816,
        make: "Porsche",
        model: "Cayman",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "473.62",
        available: true,
    },
    {
        id: 1011,
        make: "Kia",
        model: "Sportage",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "845.91",
        available: true,
    },
    {
        id: 2374,
        make: "Jeep",
        model: "Cherokee",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "594.07",
        available: true,
    },
    {
        id: 631,
        make: "Honda",
        model: "Passport",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "344.40",
        available: true,
    },
    {
        id: 1842,
        make: "Ford",
        model: "Taurus",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "848.41",
        available: true,
    },
    {
        id: 858,
        make: "Tesla",
        model: "Model S",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "444.05",
        available: true,
    },
    {
        id: 924,
        make: "Volkswagen",
        model: "Passat",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "508.37",
        available: true,
    },
    {
        id: 1842,
        make: "Toyota",
        model: "Corolla",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "311.37",
        available: true,
    },
    {
        id: 1780,
        make: "BMW",
        model: "series 1",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "581.39",
        available: true,
    },
    {
        id: 2485,
        make: "Porsche",
        model: "Boxter",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "534.48",
        available: true,
    },
    {
        id: 1923,
        make: "Kia",
        model: "Telluride",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "772.14",
        available: true,
    },
    {
        id: 2231,
        make: "Jeep",
        model: "Cherokee",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "280.88",
        available: true,
    },
    {
        id: 1945,
        make: "Honda",
        model: "Passport",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "604.99",
        available: true,
    },
    {
        id: 1891,
        make: "Ford",
        model: "Taurus",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "286.83",
        available: true,
    },
    {
        id: 1738,
        make: "Tesla",
        model: "Model Y",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "836.46",
        available: true,
    },
    {
        id: 1426,
        make: "Volkswagen",
        model: "Passat",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "675.07",
        available: true,
    },
    {
        id: 1604,
        make: "Toyota",
        model: "Prius",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "277.31",
        available: true,
    },
    {
        id: 1286,
        make: "BMW",
        model: "series 2",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "716.61",
        available: true,
    },
    {
        id: 1274,
        make: "Porsche",
        model: "Boxter",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "418.99",
        available: true,
    },
    {
        id: 1292,
        make: "Kia",
        model: "Soul",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "52.60",
        available: true,
    },
    {
        id: 555,
        make: "Jeep",
        model: "Liberty",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "571.12",
        available: true,
    },
    {
        id: 2059,
        make: "Honda",
        model: "Civic",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "407.02",
        available: true,
    },
    {
        id: 2018,
        make: "Ford",
        model: "F150",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "131.10",
        available: true,
    },
    {
        id: 1475,
        make: "Tesla",
        model: "Model 3",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "285.74",
        available: true,
    },
    {
        id: 2090,
        make: "Volkswagen",
        model: "Passat",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "543.40",
        available: true,
    },
    {
        id: 999,
        make: "Toyota",
        model: "Corolla",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "221.21",
        available: true,
    },
    {
        id: 1834,
        make: "BMW",
        model: "series 2",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "214.08",
        available: true,
    },
    {
        id: 2176,
        make: "Porsche",
        model: "Boxter",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "836.93",
        available: true,
    },
    {
        id: 828,
        make: "Kia",
        model: "Sportage",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "100.61",
        available: true,
    },
    {
        id: 1849,
        make: "Jeep",
        model: "Liberty",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "975.40",
        available: true,
    },
    {
        id: 1464,
        make: "Honda",
        model: "Accord",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "828.11",
        available: true,
    },
    {
        id: 1224,
        make: "Ford",
        model: "F150",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "786.78",
        available: true,
    },
    {
        id: 501,
        make: "Tesla",
        model: "Model Y",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "367.28",
        available: true,
    },
    {
        id: 1388,
        make: "Volkswagen",
        model: "Passat",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "928.15",
        available: true,
    },
    {
        id: 1115,
        make: "Toyota",
        model: "Prius",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "602.63",
        available: true,
    },
    {
        id: 1513,
        make: "BMW",
        model: "series 1",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "125.01",
        available: true,
    },
    {
        id: 1896,
        make: "Porsche",
        model: "Boxter",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "997.90",
        available: true,
    },
    {
        id: 768,
        make: "Kia",
        model: "Telluride",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "744.70",
        available: true,
    },
    {
        id: 826,
        make: "Jeep",
        model: "Liberty",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "402.84",
        available: true,
    },
    {
        id: 1786,
        make: "Honda",
        model: "Civic",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "458.61",
        available: true,
    },
    {
        id: 614,
        make: "Ford",
        model: "Mustang",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "624.38",
        available: true,
    },
    {
        id: 1198,
        make: "Tesla",
        model: "Model S",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "176.68",
        available: true,
    },
    {
        id: 963,
        make: "Volkswagen",
        model: "Passat",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "738.89",
        available: true,
    },
    {
        id: 805,
        make: "Toyota",
        model: "Prius",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "589.77",
        available: true,
    },
    {
        id: 1321,
        make: "BMW",
        model: "series 1",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "941.39",
        available: true,
    },
    {
        id: 1296,
        make: "Porsche",
        model: "Cayman",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "676.99",
        available: true,
    },
    {
        id: 1994,
        make: "Kia",
        model: "Soul",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "476.91",
        available: true,
    },
    {
        id: 2014,
        make: "Jeep",
        model: "Sport",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "352.20",
        available: true,
    },
    {
        id: 711,
        make: "Honda",
        model: "Accord",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "73.50",
        available: true,
    },
    {
        id: 591,
        make: "Ford",
        model: "Taurus",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "845.43",
        available: true,
    },
    {
        id: 1413,
        make: "Tesla",
        model: "Model 3",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "923.45",
        available: true,
    },
    {
        id: 2308,
        make: "Volkswagen",
        model: "Passat",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "600.45",
        available: true,
    },
    {
        id: 2070,
        make: "Toyota",
        model: "Camry",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "355.06",
        available: true,
    },
    {
        id: 1225,
        make: "BMW",
        model: "series 1",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "363.46",
        available: true,
    },
    {
        id: 2255,
        make: "Porsche",
        model: "Boxter",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "772.03",
        available: true,
    },
    {
        id: 689,
        make: "Kia",
        model: "Sportage",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "755.25",
        available: true,
    },
    {
        id: 1530,
        make: "Jeep",
        model: "Cherokee",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "431.84",
        available: true,
    },
    {
        id: 717,
        make: "Honda",
        model: "Accord",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "786.01",
        available: true,
    },
    {
        id: 2480,
        make: "Ford",
        model: "Taurus",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "394.44",
        available: true,
    },
    {
        id: 1823,
        make: "Tesla",
        model: "Model S",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "668.50",
        available: true,
    },
    {
        id: 1552,
        make: "Volkswagen",
        model: "Golf",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "194.33",
        available: true,
    },
    {
        id: 1923,
        make: "Toyota",
        model: "Camry",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "680.57",
        available: true,
    },
    {
        id: 1709,
        make: "BMW",
        model: "series 2",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "740.98",
        available: true,
    },
    {
        id: 1419,
        make: "Porsche",
        model: "Boxter",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "130.20",
        available: true,
    },
    {
        id: 1700,
        make: "Kia",
        model: "Sportage",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "736.66",
        available: true,
    },
    {
        id: 2081,
        make: "Jeep",
        model: "Sport",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "215.87",
        available: true,
    },
    {
        id: 827,
        make: "Honda",
        model: "Civic",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "794.11",
        available: true,
    },
    {
        id: 1147,
        make: "Ford",
        model: "F150",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "47.25",
        available: true,
    },
    {
        id: 1525,
        make: "Tesla",
        model: "Model 3",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "987.96",
        available: true,
    },
    {
        id: 1630,
        make: "Volkswagen",
        model: "Golf",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "201.72",
        available: true,
    },
    {
        id: 822,
        make: "Toyota",
        model: "Camry",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "716.92",
        available: true,
    },
    {
        id: 2080,
        make: "BMW",
        model: "series 1",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "975.93",
        available: true,
    },
    {
        id: 1824,
        make: "Porsche",
        model: "Boxter",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "81.40",
        available: true,
    },
    {
        id: 2428,
        make: "Kia",
        model: "Telluride",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "43.57",
        available: true,
    },
    {
        id: 1859,
        make: "Jeep",
        model: "Cherokee",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "427.72",
        available: true,
    },
    {
        id: 1289,
        make: "Honda",
        model: "Passport",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "194.18",
        available: true,
    },
    {
        id: 914,
        make: "Ford",
        model: "F150",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "358.87",
        available: true,
    },
    {
        id: 1600,
        make: "Tesla",
        model: "Model S",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "45.28",
        available: true,
    },
    {
        id: 571,
        make: "Volkswagen",
        model: "Passat",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "650.42",
        available: true,
    },
    {
        id: 1715,
        make: "Toyota",
        model: "Corolla",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "660.62",
        available: true,
    },
    {
        id: 1618,
        make: "BMW",
        model: "series 2",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "74.79",
        available: true,
    },
    {
        id: 1204,
        make: "Porsche",
        model: "Cayman",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "405.34",
        available: true,
    },
    {
        id: 1722,
        make: "Kia",
        model: "Telluride",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "139.72",
        available: true,
    },
    {
        id: 1887,
        make: "Jeep",
        model: "Sport",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "617.85",
        available: true,
    },
    {
        id: 2038,
        make: "Honda",
        model: "Passport",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "387.18",
        available: true,
    },
    {
        id: 1561,
        make: "Ford",
        model: "Mustang",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "137.31",
        available: true,
    },
    {
        id: 1695,
        make: "Tesla",
        model: "Model S",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "679.69",
        available: true,
    },
    {
        id: 2294,
        make: "Volkswagen",
        model: "Passat",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "61.72",
        available: true,
    },
    {
        id: 854,
        make: "Toyota",
        model: "Corolla",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "230.63",
        available: true,
    },
    {
        id: 1061,
        make: "BMW",
        model: "series 1",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "469.89",
        available: true,
    },
    {
        id: 1803,
        make: "Porsche",
        model: "Boxter",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "246.18",
        available: true,
    },
    {
        id: 1250,
        make: "Kia",
        model: "Soul",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "650.23",
        available: true,
    },
    {
        id: 776,
        make: "Jeep",
        model: "Sport",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "952.32",
        available: true,
    },
    {
        id: 912,
        make: "Honda",
        model: "Passport",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "615.65",
        available: true,
    },
    {
        id: 621,
        make: "Ford",
        model: "Mustang",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "685.41",
        available: true,
    },
    {
        id: 1595,
        make: "Tesla",
        model: "Model S",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "190.98",
        available: true,
    },
    {
        id: 1424,
        make: "Volkswagen",
        model: "Golf",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "555.67",
        available: true,
    },
    {
        id: 664,
        make: "Toyota",
        model: "Corolla",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "736.65",
        available: true,
    },
    {
        id: 1263,
        make: "BMW",
        model: "series 2",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "185.40",
        available: true,
    },
    {
        id: 2342,
        make: "Porsche",
        model: "Boxter",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "648.83",
        available: true,
    },
    {
        id: 2246,
        make: "Kia",
        model: "Soul",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "643.07",
        available: true,
    },
    {
        id: 1898,
        make: "Jeep",
        model: "Cherokee",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "198.29",
        available: true,
    },
    {
        id: 1987,
        make: "Honda",
        model: "Passport",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "508.92",
        available: true,
    },
    {
        id: 993,
        make: "Ford",
        model: "Taurus",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "388.79",
        available: true,
    },
    {
        id: 618,
        make: "Tesla",
        model: "Model S",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "858.53",
        available: true,
    },
    {
        id: 1526,
        make: "Volkswagen",
        model: "Passat",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "334.18",
        available: true,
    },
    {
        id: 933,
        make: "Toyota",
        model: "Prius",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "609.68",
        available: true,
    },
    {
        id: 707,
        make: "BMW",
        model: "series 1",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "976.23",
        available: true,
    },
    {
        id: 1991,
        make: "Porsche",
        model: "Boxter",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "901.18",
        available: true,
    },
    {
        id: 2276,
        make: "Kia",
        model: "Soul",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "603.11",
        available: true,
    },
    {
        id: 1685,
        make: "Jeep",
        model: "Liberty",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "128.66",
        available: true,
    },
    {
        id: 506,
        make: "Honda",
        model: "Civic",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "729.16",
        available: true,
    },
    {
        id: 898,
        make: "Ford",
        model: "Taurus",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "662.61",
        available: true,
    },
    {
        id: 2063,
        make: "Tesla",
        model: "Model 3",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "702.17",
        available: true,
    },
    {
        id: 1427,
        make: "Volkswagen",
        model: "Golf",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "694.83",
        available: true,
    },
    {
        id: 1046,
        make: "Toyota",
        model: "Corolla",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "786.68",
        available: true,
    },
    {
        id: 722,
        make: "BMW",
        model: "series 2",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "592.38",
        available: true,
    },
    {
        id: 1748,
        make: "Porsche",
        model: "Boxter",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "783.73",
        available: true,
    },
    {
        id: 881,
        make: "Kia",
        model: "Soul",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "508.03",
        available: true,
    },
    {
        id: 1377,
        make: "Jeep",
        model: "Cherokee",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "477.18",
        available: true,
    },
    {
        id: 1025,
        make: "Honda",
        model: "Accord",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "93.67",
        available: true,
    },
    {
        id: 1790,
        make: "Ford",
        model: "F150",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "785.11",
        available: true,
    },
    {
        id: 2085,
        make: "Tesla",
        model: "Model S",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "251.96",
        available: true,
    },
    {
        id: 618,
        make: "Volkswagen",
        model: "Passat",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "370.14",
        available: true,
    },
    {
        id: 2197,
        make: "Toyota",
        model: "Prius",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "863.91",
        available: true,
    },
    {
        id: 1214,
        make: "BMW",
        model: "series 1",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "410.62",
        available: true,
    },
    {
        id: 502,
        make: "Porsche",
        model: "Boxter",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "269.14",
        available: true,
    },
    {
        id: 714,
        make: "Kia",
        model: "Sportage",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "346.17",
        available: true,
    },
    {
        id: 523,
        make: "Jeep",
        model: "Liberty",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "360.26",
        available: true,
    },
    {
        id: 2104,
        make: "Honda",
        model: "Civic",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "696.81",
        available: true,
    },
    {
        id: 899,
        make: "Ford",
        model: "Mustang",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "835.77",
        available: true,
    },
    {
        id: 2129,
        make: "Tesla",
        model: "Model Y",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "882.00",
        available: true,
    },
    {
        id: 2458,
        make: "Volkswagen",
        model: "Passat",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "554.36",
        available: true,
    },
    {
        id: 763,
        make: "Toyota",
        model: "Prius",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "236.60",
        available: true,
    },
    {
        id: 1869,
        make: "BMW",
        model: "series 1",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "685.26",
        available: true,
    },
    {
        id: 1685,
        make: "Porsche",
        model: "Cayman",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "119.91",
        available: true,
    },
    {
        id: 1943,
        make: "Kia",
        model: "Soul",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "17.00",
        available: true,
    },
    {
        id: 1850,
        make: "Jeep",
        model: "Liberty",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "783.70",
        available: true,
    },
    {
        id: 1426,
        make: "Honda",
        model: "Passport",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "467.27",
        available: true,
    },
    {
        id: 2367,
        make: "Ford",
        model: "Mustang",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "90.88",
        available: true,
    },
    {
        id: 675,
        make: "Tesla",
        model: "Model Y",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "231.89",
        available: true,
    },
    {
        id: 2148,
        make: "Volkswagen",
        model: "Golf",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "359.37",
        available: true,
    },
    {
        id: 1439,
        make: "Toyota",
        model: "Prius",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "881.93",
        available: true,
    },
    {
        id: 1154,
        make: "BMW",
        model: "series 1",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "588.35",
        available: true,
    },
    {
        id: 843,
        make: "Porsche",
        model: "Boxter",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "446.87",
        available: true,
    },
    {
        id: 1751,
        make: "Kia",
        model: "Sportage",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "503.05",
        available: true,
    },
    {
        id: 2107,
        make: "Jeep",
        model: "Liberty",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "853.63",
        available: true,
    },
    {
        id: 2192,
        make: "Honda",
        model: "Civic",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "827.25",
        available: true,
    },
    {
        id: 1336,
        make: "Ford",
        model: "Mustang",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "860.06",
        available: true,
    },
    {
        id: 1248,
        make: "Tesla",
        model: "Model Y",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "545.52",
        available: true,
    },
    {
        id: 1305,
        make: "Volkswagen",
        model: "Golf",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "476.13",
        available: true,
    },
    {
        id: 1709,
        make: "Toyota",
        model: "Camry",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "733.98",
        available: true,
    },
    {
        id: 1768,
        make: "BMW",
        model: "series 2",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "155.28",
        available: true,
    },
    {
        id: 1518,
        make: "Porsche",
        model: "Boxter",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "242.22",
        available: true,
    },
    {
        id: 871,
        make: "Kia",
        model: "Sportage",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "780.85",
        available: true,
    },
    {
        id: 1793,
        make: "Jeep",
        model: "Cherokee",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "179.39",
        available: true,
    },
    {
        id: 979,
        make: "Honda",
        model: "Accord",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "668.50",
        available: true,
    },
    {
        id: 2379,
        make: "Ford",
        model: "Taurus",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "861.11",
        available: true,
    },
    {
        id: 2252,
        make: "Tesla",
        model: "Model S",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "374.32",
        available: true,
    },
    {
        id: 596,
        make: "Volkswagen",
        model: "Passat",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "81.84",
        available: true,
    },
    {
        id: 1651,
        make: "Toyota",
        model: "Corolla",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "128.87",
        available: true,
    },
    {
        id: 1490,
        make: "BMW",
        model: "series 1",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "430.85",
        available: true,
    },
    {
        id: 1456,
        make: "Porsche",
        model: "Cayman",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "758.19",
        available: true,
    },
    {
        id: 1724,
        make: "Kia",
        model: "Telluride",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "714.21",
        available: true,
    },
    {
        id: 778,
        make: "Jeep",
        model: "Liberty",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "318.45",
        available: true,
    },
    {
        id: 1659,
        make: "Honda",
        model: "Civic",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "70.22",
        available: true,
    },
    {
        id: 1401,
        make: "Ford",
        model: "Mustang",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "959.66",
        available: true,
    },
    {
        id: 895,
        make: "Tesla",
        model: "Model S",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "115.36",
        available: true,
    },
    {
        id: 1411,
        make: "Volkswagen",
        model: "Passat",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "388.09",
        available: true,
    },
    {
        id: 1138,
        make: "Toyota",
        model: "Camry",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "797.37",
        available: true,
    },
    {
        id: 2021,
        make: "BMW",
        model: "series 1",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "142.05",
        available: true,
    },
    {
        id: 542,
        make: "Porsche",
        model: "Boxter",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "27.18",
        available: true,
    },
    {
        id: 2003,
        make: "Kia",
        model: "Soul",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "993.10",
        available: true,
    },
    {
        id: 849,
        make: "Jeep",
        model: "Sport",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "5.73",
        available: true,
    },
    {
        id: 1573,
        make: "Honda",
        model: "Passport",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "668.97",
        available: true,
    },
    {
        id: 1792,
        make: "Ford",
        model: "F150",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "899.82",
        available: true,
    },
    {
        id: 2486,
        make: "Tesla",
        model: "Model Y",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "199.59",
        available: true,
    },
    {
        id: 2312,
        make: "Volkswagen",
        model: "Golf",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "45.04",
        available: true,
    },
    {
        id: 1524,
        make: "Toyota",
        model: "Corolla",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "509.07",
        available: true,
    },
    {
        id: 1666,
        make: "BMW",
        model: "series 1",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "163.06",
        available: true,
    },
    {
        id: 1193,
        make: "Porsche",
        model: "Boxter",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "971.72",
        available: true,
    },
    {
        id: 687,
        make: "Kia",
        model: "Sportage",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "582.38",
        available: true,
    },
    {
        id: 643,
        make: "Jeep",
        model: "Liberty",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "707.83",
        available: true,
    },
    {
        id: 2424,
        make: "Honda",
        model: "Accord",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "840.39",
        available: true,
    },
    {
        id: 1649,
        make: "Ford",
        model: "Mustang",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "471.80",
        available: true,
    },
    {
        id: 2334,
        make: "Tesla",
        model: "Model 3",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "599.28",
        available: true,
    },
    {
        id: 759,
        make: "Volkswagen",
        model: "Golf",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "825.51",
        available: true,
    },
    {
        id: 746,
        make: "Toyota",
        model: "Prius",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "209.89",
        available: true,
    },
    {
        id: 1628,
        make: "BMW",
        model: "series 2",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "690.62",
        available: true,
    },
    {
        id: 1443,
        make: "Porsche",
        model: "Boxter",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "596.32",
        available: true,
    },
    {
        id: 572,
        make: "Kia",
        model: "Telluride",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "496.46",
        available: true,
    },
    {
        id: 2096,
        make: "Jeep",
        model: "Cherokee",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "904.23",
        available: true,
    },
    {
        id: 540,
        make: "Honda",
        model: "Civic",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "47.60",
        available: true,
    },
    {
        id: 1455,
        make: "Ford",
        model: "Mustang",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "151.53",
        available: true,
    },
    {
        id: 2088,
        make: "Tesla",
        model: "Model Y",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "984.26",
        available: true,
    },
    {
        id: 1274,
        make: "Volkswagen",
        model: "Golf",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "994.58",
        available: true,
    },
    {
        id: 1486,
        make: "Toyota",
        model: "Camry",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "661.33",
        available: true,
    },
    {
        id: 2133,
        make: "BMW",
        model: "series 1",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "673.80",
        available: true,
    },
    {
        id: 2211,
        make: "Porsche",
        model: "Cayman",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "338.88",
        available: true,
    },
    {
        id: 2003,
        make: "Kia",
        model: "Sportage",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "994.72",
        available: true,
    },
    {
        id: 1800,
        make: "Jeep",
        model: "Cherokee",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "810.53",
        available: true,
    },
    {
        id: 1111,
        make: "Honda",
        model: "Passport",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "779.33",
        available: true,
    },
    {
        id: 1169,
        make: "Ford",
        model: "Taurus",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "709.34",
        available: true,
    },
    {
        id: 776,
        make: "Tesla",
        model: "Model Y",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "189.62",
        available: true,
    },
    {
        id: 1034,
        make: "Volkswagen",
        model: "Golf",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "420.49",
        available: true,
    },
    {
        id: 1358,
        make: "Toyota",
        model: "Prius",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "211.12",
        available: true,
    },
    {
        id: 1184,
        make: "BMW",
        model: "series 1",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "750.23",
        available: true,
    },
    {
        id: 2291,
        make: "Porsche",
        model: "Boxter",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "813.42",
        available: true,
    },
    {
        id: 1355,
        make: "Kia",
        model: "Telluride",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "556.29",
        available: true,
    },
    {
        id: 1515,
        make: "Jeep",
        model: "Sport",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "99.22",
        available: true,
    },
    {
        id: 2435,
        make: "Honda",
        model: "Passport",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "934.54",
        available: true,
    },
    {
        id: 1150,
        make: "Ford",
        model: "F150",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "182.88",
        available: true,
    },
    {
        id: 891,
        make: "Tesla",
        model: "Model Y",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "809.32",
        available: true,
    },
    {
        id: 2114,
        make: "Volkswagen",
        model: "Passat",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "374.90",
        available: true,
    },
    {
        id: 1531,
        make: "Toyota",
        model: "Prius",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "919.93",
        available: true,
    },
    {
        id: 1656,
        make: "BMW",
        model: "series 1",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "117.83",
        available: true,
    },
    {
        id: 1167,
        make: "Porsche",
        model: "Cayman",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "165.86",
        available: true,
    },
    {
        id: 753,
        make: "Kia",
        model: "Soul",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "453.95",
        available: true,
    },
    {
        id: 2263,
        make: "Jeep",
        model: "Sport",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "786.85",
        available: true,
    },
    {
        id: 565,
        make: "Honda",
        model: "Civic",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "401.05",
        available: true,
    },
    {
        id: 1699,
        make: "Ford",
        model: "Taurus",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "294.14",
        available: true,
    },
    {
        id: 1081,
        make: "Tesla",
        model: "Model 3",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "868.78",
        available: true,
    },
    {
        id: 816,
        make: "Volkswagen",
        model: "Golf",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "842.68",
        available: true,
    },
    {
        id: 1786,
        make: "Toyota",
        model: "Corolla",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "488.89",
        available: true,
    },
    {
        id: 686,
        make: "BMW",
        model: "series 1",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "952.31",
        available: true,
    },
    {
        id: 2220,
        make: "Porsche",
        model: "Cayman",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "805.15",
        available: true,
    },
    {
        id: 630,
        make: "Kia",
        model: "Sportage",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "255.73",
        available: true,
    },
    {
        id: 2438,
        make: "Jeep",
        model: "Sport",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "961.06",
        available: true,
    },
    {
        id: 656,
        make: "Honda",
        model: "Accord",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "141.72",
        available: true,
    },
    {
        id: 1890,
        make: "Ford",
        model: "Taurus",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "694.23",
        available: true,
    },
    {
        id: 737,
        make: "Tesla",
        model: "Model Y",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "142.17",
        available: true,
    },
    {
        id: 2348,
        make: "Volkswagen",
        model: "Golf",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "211.42",
        available: true,
    },
    {
        id: 2190,
        make: "Toyota",
        model: "Corolla",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "171.38",
        available: true,
    },
    {
        id: 1714,
        make: "BMW",
        model: "series 1",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "799.38",
        available: true,
    },
    {
        id: 1460,
        make: "Porsche",
        model: "Boxter",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "545.80",
        available: true,
    },
    {
        id: 881,
        make: "Kia",
        model: "Soul",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "504.43",
        available: true,
    },
    {
        id: 1706,
        make: "Jeep",
        model: "Cherokee",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "85.00",
        available: true,
    },
    {
        id: 1609,
        make: "Honda",
        model: "Civic",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "157.17",
        available: true,
    },
    {
        id: 1526,
        make: "Ford",
        model: "Mustang",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "570.00",
        available: true,
    },
    {
        id: 2289,
        make: "Tesla",
        model: "Model S",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "54.96",
        available: true,
    },
    {
        id: 2284,
        make: "Volkswagen",
        model: "Golf",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "606.34",
        available: true,
    },
    {
        id: 622,
        make: "Toyota",
        model: "Prius",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "870.59",
        available: true,
    },
    {
        id: 1072,
        make: "BMW",
        model: "series 1",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "174.79",
        available: true,
    },
    {
        id: 2050,
        make: "Porsche",
        model: "Boxter",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "3.07",
        available: true,
    },
    {
        id: 1560,
        make: "Kia",
        model: "Telluride",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "884.81",
        available: true,
    },
    {
        id: 1325,
        make: "Jeep",
        model: "Liberty",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "121.12",
        available: true,
    },
    {
        id: 1236,
        make: "Honda",
        model: "Accord",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "142.76",
        available: true,
    },
    {
        id: 1522,
        make: "Ford",
        model: "Taurus",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "981.27",
        available: true,
    },
    {
        id: 1520,
        make: "Tesla",
        model: "Model Y",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "460.96",
        available: true,
    },
    {
        id: 2021,
        make: "Volkswagen",
        model: "Passat",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "422.58",
        available: true,
    },
    {
        id: 503,
        make: "Toyota",
        model: "Camry",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "328.12",
        available: true,
    },
    {
        id: 927,
        make: "BMW",
        model: "series 2",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "59.46",
        available: true,
    },
    {
        id: 1852,
        make: "Porsche",
        model: "Boxter",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "917.78",
        available: true,
    },
    {
        id: 1315,
        make: "Kia",
        model: "Soul",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "114.12",
        available: true,
    },
    {
        id: 1211,
        make: "Jeep",
        model: "Cherokee",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "565.34",
        available: true,
    },
    {
        id: 1568,
        make: "Honda",
        model: "Accord",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "478.29",
        available: true,
    },
    {
        id: 1678,
        make: "Ford",
        model: "Taurus",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "212.32",
        available: true,
    },
    {
        id: 2296,
        make: "Tesla",
        model: "Model S",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "268.44",
        available: true,
    },
    {
        id: 758,
        make: "Volkswagen",
        model: "Golf",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "212.63",
        available: true,
    },
    {
        id: 2296,
        make: "Toyota",
        model: "Corolla",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "944.41",
        available: true,
    },
    {
        id: 503,
        make: "BMW",
        model: "series 2",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "860.17",
        available: true,
    },
    {
        id: 765,
        make: "Porsche",
        model: "Boxter",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "313.19",
        available: true,
    },
    {
        id: 1273,
        make: "Kia",
        model: "Sportage",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "526.83",
        available: true,
    },
    {
        id: 1280,
        make: "Jeep",
        model: "Sport",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "870.76",
        available: true,
    },
    {
        id: 1793,
        make: "Honda",
        model: "Civic",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "936.17",
        available: true,
    },
    {
        id: 1792,
        make: "Ford",
        model: "Mustang",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "38.76",
        available: true,
    },
    {
        id: 2143,
        make: "Tesla",
        model: "Model S",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "964.93",
        available: true,
    },
    {
        id: 1758,
        make: "Volkswagen",
        model: "Golf",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "624.54",
        available: true,
    },
    {
        id: 934,
        make: "Toyota",
        model: "Camry",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "144.86",
        available: true,
    },
    {
        id: 1554,
        make: "BMW",
        model: "series 2",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "65.75",
        available: true,
    },
    {
        id: 1191,
        make: "Porsche",
        model: "Cayman",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "931.57",
        available: true,
    },
    {
        id: 2251,
        make: "Kia",
        model: "Telluride",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "412.15",
        available: true,
    },
    {
        id: 1986,
        make: "Jeep",
        model: "Cherokee",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "721.94",
        available: true,
    },
    {
        id: 2321,
        make: "Honda",
        model: "Accord",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "143.91",
        available: true,
    },
    {
        id: 784,
        make: "Ford",
        model: "Mustang",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "575.54",
        available: true,
    },
    {
        id: 1174,
        make: "Tesla",
        model: "Model 3",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "506.35",
        available: true,
    },
    {
        id: 820,
        make: "Volkswagen",
        model: "Passat",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "224.87",
        available: true,
    },
    {
        id: 759,
        make: "Toyota",
        model: "Corolla",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "493.12",
        available: true,
    },
    {
        id: 883,
        make: "BMW",
        model: "series 1",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "256.69",
        available: true,
    },
    {
        id: 2496,
        make: "Porsche",
        model: "Boxter",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "261.87",
        available: true,
    },
    {
        id: 1787,
        make: "Kia",
        model: "Sportage",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "247.91",
        available: true,
    },
    {
        id: 1444,
        make: "Jeep",
        model: "Liberty",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "956.68",
        available: true,
    },
    {
        id: 1386,
        make: "Honda",
        model: "Accord",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "175.14",
        available: true,
    },
    {
        id: 841,
        make: "Ford",
        model: "Mustang",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "441.92",
        available: true,
    },
    {
        id: 2439,
        make: "Tesla",
        model: "Model 3",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "101.37",
        available: true,
    },
    {
        id: 1196,
        make: "Volkswagen",
        model: "Golf",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "171.28",
        available: true,
    },
    {
        id: 1402,
        make: "Toyota",
        model: "Prius",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "618.07",
        available: true,
    },
    {
        id: 1486,
        make: "BMW",
        model: "series 1",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "182.62",
        available: true,
    },
    {
        id: 671,
        make: "Porsche",
        model: "Boxter",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "642.50",
        available: true,
    },
    {
        id: 1356,
        make: "Kia",
        model: "Sportage",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "983.71",
        available: true,
    },
    {
        id: 1617,
        make: "Jeep",
        model: "Sport",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "942.25",
        available: true,
    },
    {
        id: 723,
        make: "Honda",
        model: "Passport",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "29.94",
        available: true,
    },
    {
        id: 1668,
        make: "Ford",
        model: "F150",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "293.37",
        available: true,
    },
    {
        id: 2215,
        make: "Tesla",
        model: "Model 3",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "22.34",
        available: true,
    },
    {
        id: 1856,
        make: "Volkswagen",
        model: "Passat",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "523.43",
        available: true,
    },
    {
        id: 541,
        make: "Toyota",
        model: "Corolla",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "193.17",
        available: true,
    },
    {
        id: 1356,
        make: "BMW",
        model: "series 1",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "844.68",
        available: true,
    },
    {
        id: 2415,
        make: "Porsche",
        model: "Cayman",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "888.31",
        available: true,
    },
    {
        id: 1402,
        make: "Kia",
        model: "Sportage",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "842.81",
        available: true,
    },
    {
        id: 2192,
        make: "Jeep",
        model: "Sport",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "661.29",
        available: true,
    },
    {
        id: 2045,
        make: "Honda",
        model: "Accord",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "673.48",
        available: true,
    },
    {
        id: 1589,
        make: "Ford",
        model: "Mustang",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "785.38",
        available: true,
    },
    {
        id: 2075,
        make: "Tesla",
        model: "Model Y",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "770.44",
        available: true,
    },
    {
        id: 1753,
        make: "Volkswagen",
        model: "Golf",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "79.76",
        available: true,
    },
    {
        id: 520,
        make: "Toyota",
        model: "Prius",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "748.17",
        available: true,
    },
    {
        id: 2155,
        make: "BMW",
        model: "series 1",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "180.97",
        available: true,
    },
    {
        id: 1055,
        make: "Porsche",
        model: "Boxter",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "39.66",
        available: true,
    },
    {
        id: 2030,
        make: "Kia",
        model: "Sportage",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "824.19",
        available: true,
    },
    {
        id: 2489,
        make: "Jeep",
        model: "Sport",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "118.43",
        available: true,
    },
    {
        id: 981,
        make: "Honda",
        model: "Accord",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "811.76",
        available: true,
    },
    {
        id: 2169,
        make: "Ford",
        model: "Mustang",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "602.25",
        available: true,
    },
    {
        id: 1684,
        make: "Tesla",
        model: "Model Y",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "857.03",
        available: true,
    },
    {
        id: 790,
        make: "Volkswagen",
        model: "Passat",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "752.64",
        available: true,
    },
    {
        id: 1664,
        make: "Toyota",
        model: "Corolla",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "161.26",
        available: true,
    },
    {
        id: 1727,
        make: "BMW",
        model: "series 1",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "877.61",
        available: true,
    },
    {
        id: 736,
        make: "Porsche",
        model: "Boxter",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "850.46",
        available: true,
    },
    {
        id: 1199,
        make: "Kia",
        model: "Sportage",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "243.43",
        available: true,
    },
    {
        id: 1321,
        make: "Jeep",
        model: "Cherokee",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "635.38",
        available: true,
    },
    {
        id: 1050,
        make: "Honda",
        model: "Passport",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "959.46",
        available: true,
    },
    {
        id: 546,
        make: "Ford",
        model: "Taurus",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "263.56",
        available: true,
    },
    {
        id: 1523,
        make: "Tesla",
        model: "Model Y",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "111.76",
        available: true,
    },
    {
        id: 2005,
        make: "Volkswagen",
        model: "Passat",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "12.03",
        available: true,
    },
    {
        id: 633,
        make: "Toyota",
        model: "Camry",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "156.23",
        available: true,
    },
    {
        id: 1688,
        make: "BMW",
        model: "series 2",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "209.27",
        available: true,
    },
    {
        id: 561,
        make: "Porsche",
        model: "Cayman",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "966.33",
        available: true,
    },
    {
        id: 1746,
        make: "Kia",
        model: "Sportage",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "762.79",
        available: true,
    },
    {
        id: 714,
        make: "Jeep",
        model: "Cherokee",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "13.34",
        available: true,
    },
    {
        id: 1413,
        make: "Honda",
        model: "Passport",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "146.75",
        available: true,
    },
    {
        id: 1921,
        make: "Ford",
        model: "F150",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "830.68",
        available: true,
    },
    {
        id: 2148,
        make: "Tesla",
        model: "Model Y",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "519.85",
        available: true,
    },
    {
        id: 1526,
        make: "Volkswagen",
        model: "Golf",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "395.61",
        available: true,
    },
    {
        id: 1742,
        make: "Toyota",
        model: "Corolla",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "994.87",
        available: true,
    },
    {
        id: 1109,
        make: "BMW",
        model: "series 1",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "581.32",
        available: true,
    },
    {
        id: 2019,
        make: "Porsche",
        model: "Cayman",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "29.00",
        available: true,
    },
    {
        id: 2327,
        make: "Kia",
        model: "Telluride",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "880.78",
        available: true,
    },
    {
        id: 2048,
        make: "Jeep",
        model: "Liberty",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "417.37",
        available: true,
    },
    {
        id: 2387,
        make: "Honda",
        model: "Accord",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "291.07",
        available: true,
    },
    {
        id: 1844,
        make: "Ford",
        model: "Mustang",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "227.84",
        available: true,
    },
    {
        id: 2302,
        make: "Tesla",
        model: "Model 3",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "506.73",
        available: true,
    },
    {
        id: 729,
        make: "Volkswagen",
        model: "Passat",
        year: 2011,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "146.50",
        available: true,
    },
    {
        id: 537,
        make: "Toyota",
        model: "Prius",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "402.03",
        available: true,
    },
    {
        id: 1690,
        make: "BMW",
        model: "series 1",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "912.45",
        available: true,
    },
    {
        id: 2092,
        make: "Porsche",
        model: "Cayman",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "579.41",
        available: true,
    },
    {
        id: 506,
        make: "Kia",
        model: "Soul",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "781.21",
        available: true,
    },
    {
        id: 1108,
        make: "Jeep",
        model: "Cherokee",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "587.67",
        available: true,
    },
    {
        id: 2217,
        make: "Honda",
        model: "Civic",
        year: 2002,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "612.11",
        available: true,
    },
    {
        id: 694,
        make: "Ford",
        model: "Mustang",
        year: 2000,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "721.75",
        available: true,
    },
    {
        id: 1708,
        make: "Tesla",
        model: "Model S",
        year: 2004,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "483.73",
        available: true,
    },
    {
        id: 1380,
        make: "Volkswagen",
        model: "Passat",
        year: 2009,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "141.33",
        available: true,
    },
    {
        id: 2250,
        make: "Toyota",
        model: "Corolla",
        year: 2003,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "760.32",
        available: true,
    },
    {
        id: 639,
        make: "BMW",
        model: "series 1",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "452.68",
        available: true,
    },
    {
        id: 825,
        make: "Porsche",
        model: "Cayman",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "227.99",
        available: true,
    },
    {
        id: 2430,
        make: "Kia",
        model: "Soul",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "874.50",
        available: true,
    },
    {
        id: 2347,
        make: "Jeep",
        model: "Cherokee",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "300.46",
        available: true,
    },
    {
        id: 569,
        make: "Honda",
        model: "Civic",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "237.85",
        available: true,
    },
    {
        id: 650,
        make: "Ford",
        model: "Mustang",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "321.23",
        available: true,
    },
    {
        id: 2468,
        make: "Tesla",
        model: "Model S",
        year: 2007,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "807.84",
        available: true,
    },
    {
        id: 1645,
        make: "Volkswagen",
        model: "Passat",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "490.06",
        available: true,
    },
    {
        id: 2340,
        make: "Toyota",
        model: "Corolla",
        year: 2019,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "208.00",
        available: true,
    },
    {
        id: 1462,
        make: "BMW",
        model: "series 1",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "498.28",
        available: true,
    },
    {
        id: 1531,
        make: "Porsche",
        model: "Cayman",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "207.16",
        available: true,
    },
    {
        id: 780,
        make: "Kia",
        model: "Sportage",
        year: 2006,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "291.67",
        available: true,
    },
    {
        id: 631,
        make: "Jeep",
        model: "Sport",
        year: 2005,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "123.81",
        available: true,
    },
    {
        id: 1290,
        make: "Honda",
        model: "Accord",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "106.13",
        available: true,
    },
    {
        id: 830,
        make: "Ford",
        model: "F150",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Red",
        price: "518.01",
        available: true,
    },
    {
        id: 2166,
        make: "Tesla",
        model: "Model Y",
        year: 2020,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "212.05",
        available: true,
    },
    {
        id: 2465,
        make: "Volkswagen",
        model: "Golf",
        year: 2010,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "130.98",
        available: true,
    },
    {
        id: 510,
        make: "Toyota",
        model: "Corolla",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "533.16",
        available: true,
    },
    {
        id: 708,
        make: "BMW",
        model: "series 1",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "917.63",
        available: true,
    },
    {
        id: 1954,
        make: "Porsche",
        model: "Boxter",
        year: 2015,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "637.46",
        available: true,
    },
    {
        id: 2480,
        make: "Kia",
        model: "Telluride",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "139.62",
        available: true,
    },
    {
        id: 2205,
        make: "Jeep",
        model: "Liberty",
        year: 2001,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "658.10",
        available: true,
    },
    {
        id: 1720,
        make: "Honda",
        model: "Accord",
        year: 2016,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "290.40",
        available: true,
    },
    {
        id: 1526,
        make: "Ford",
        model: "F150",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "629.44",
        available: true,
    },
    {
        id: 1828,
        make: "Tesla",
        model: "Model 3",
        year: 2014,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "605.71",
        available: true,
    },
    {
        id: 1812,
        make: "Volkswagen",
        model: "Passat",
        year: 2018,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "934.44",
        available: true,
    },
    {
        id: 1685,
        make: "Toyota",
        model: "Corolla",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "827.04",
        available: true,
    },
    {
        id: 699,
        make: "BMW",
        model: "series 2",
        year: 2012,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "448.69",
        available: true,
    },
    {
        id: 2166,
        make: "Porsche",
        model: "Cayman",
        year: 2008,
        image: "https://via.placeholder.com/200",
        color: "Silver",
        price: "217.15",
        available: true,
    },
    {
        id: 1235,
        make: "Kia",
        model: "Sportage",
        year: 2013,
        image: "https://via.placeholder.com/200",
        color: "Black",
        price: "514.66",
        available: true,
    },
    {
        id: 2009,
        make: "Jeep",
        model: "Sport",
        year: 2017,
        image: "https://via.placeholder.com/200",
        color: "Blue",
        price: "401.43",
        available: true,
    },
];
